bindkey -v

export FZF_DEFAULT_OPTS='--height=40% --layout=reverse --border=sharp --color "border:#414868,bg+:#414868" --preview-window right:noborder'
export EDITOR='nvim'
export MANPAGER='nvim +Man!'
export LANG="en_GB.UTF-8"

export MENV_FILE=".mbenv"
function _check_mbpath()
{
    local check_dir="$1"

    if [[ -f "${check_dir}/${MENV_FILE}" ]]; then
        printf "${check_dir}/${MENV_FILE}"
        return
    else
        if [[ "$check_dir" = "/" || "$check_dir" = "$HOME" ]]; then
            return
        fi
        _check_mbpath "$(dirname "$check_dir")"
    fi
}

function _mbenv() {
    local mbenv_path="$(_check_mbpath "$PWD")"

    if [[ -f "$mbenv_path" ]]; then
        venv_path="$(_check_path "$PWD")"
        env_name=$(cat $mbenv_path)
        if [[ "$env_name" = "$CONDA_DEFAULT_ENV" ]]; then
            return
        elif [[ "$env_name" != "$CONDA_DEFAULT_ENV" ]]; then
                micromamba activate $env_name
        fi
        micromamba activate $env_name
        py_version=$($(which python) --version)
        echo "Switching micromamba env: ${BOLD}${PURPLE}$env_name${NORMAL} ${GREEN}[🐍 $py_version]${NORMAL}"
    elif [[ -v CONDA_DEFAULT_ENV ]]; then
            echo "Deactivating: ${BOLD}${PURPLE}$env_name${NORMAL}"
            micromamba deactivate
    fi
}

chpwd_functions=(_mbenv)

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors \
  "di=34" "ln=35" "so=32" "pi=33" "ex=31" "bd=34;46" "cd=34;43" \
  "su=30;41" "sg=30;46" "tw=30;42" "ow=30;43"
zstyle ':completion:*' menu select
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/cjber/.zshrc'

zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':fzf-tab:*' switch-group ',' '.'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'
zstyle ':fzf-tab:*' fzf-bindings 'space:accept'
zstyle ':fzf-tab:*' accept-line enter
zstyle ':fzf-tab:*' fzf-pad 4

autoload -U zmv
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
bindkey -v '^?' backward-delete-char

export PYTHON_CONFIGURE_OPTS="--enable-shared"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi
fpath+=~/.zfunc
fpath+=~/.zshcompletions/conda-zsh-completion
autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
setopt histignorealldups
HISTFILE=~/.cache/history
HISTSIZE=100000
SAVEHIST=100000
# End of lines configured by zsh-newuser-install

alias bat="bat --style=grid,numbers --theme TwoDark"
alias conf="cd $HOME/dotfiles/dotfiles; nvim \$(fzf)"
alias empty='gio trash --empty'
alias la="ncdu"
alias lf="ranger"
alias ls='exa -F --group-directories-first'
alias lg="lazygit"
alias mkvenv='mkvenv --python=$(pyenv which python)'
alias py="ipython"
alias r="radian"
alias rm="gio trash"
alias t='todo.sh list'
alias ta='todo.sh add'
alias td='nvim $HOME/todo/Dropbox/todo/todo.txt'
alias v='nvim'
alias vv='nvim $(fzf)'
alias vi='nvim'
alias mb='micromamba'
alias mvr='rsync -a --progress --remove-source-files'
alias tl="tldr --list | fzf --preview 'tldr {} --color always' | xargs tldr"

export DOTREPO="$HOME/dotfiles"
export npm_config_prefix="$HOME/.local"
export DOTDROP_PROFILE='home'
alias dotdrop='dotdrop --cfg=$HOME/dotfiles/config.yaml'
alias dotgit="git -C $DOTREPO"
alias dotsync="dotgit pull origin master && dotgit add -A && dotgit commit && dotgit push origin master; dotdrop install"
alias cb="/home/cjber/.games/battlenet/drive_c/Program\ Files\ \(x86\)/World\ of\ Warcraft/_classic_/CurseBreaker-linux"

# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

# prompt
eval "$(starship init zsh)"

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node \
    rupa/z \
    changyuheng/fz \
    Aloxaf/fzf-tab \
    zsh-users/zsh-completions \
    MichaelAquilina/zsh-autoswitch-virtualenv \
    zsh-users/zsh-autosuggestions \
    zsh-users/zsh-history-substring-search \
    zdharma/fast-syntax-highlighting

### End of Zinit's installer chunk
export GOPATH="$HOME/.go"
export PYENV_ROOT="$HOME/.pyenv"

export PATH="$GOPATH/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="/home/cjber/.cargo/bin:$PATH"
export PATH="/home/cjber/bin:$PATH"
export PATH="/home/cjber/.local/bin:$PATH"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5c6370,bold,underline"
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="fg=#bb9af7,bold,underline"

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE="/usr/bin/micromamba";
export MAMBA_ROOT_PREFIX="$HOME/.mamba";
__mamba_setup="$('/usr/bin/micromamba' shell hook --shell zsh --prefix '.mamba' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    if [ -f ".mamba/etc/profile.d/mamba.sh" ]; then
        . ".mamba/etc/profile.d/mamba.sh"
    else
        export PATH=".mamba/bin:$PATH"
    fi
fi
unset __mamba_setup
# <<< mamba initialize <<<

export PATH="$HOME/.poetry/bin:$PATH"
