config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  minversion: 1.9.0
dotfiles:
  f_rprofile:
    src: Rprofile
    dst: ~/.Rprofile
    link: absolute
  f_renviron:
    src: Renviron
    dst: ~/.Renviron
    link: absolute
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    link: absolute
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
    link: absolute
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
    link: absolute
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: absolute
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
    link: absolute
  d_ipython:
    src: ipython
    dst: ~/.ipython
    link: link_children
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: absolute
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_radian_profile:
    src: radian_profile
    dst: ~/.radian_profile
  f_condarc:
    src: condarc
    dst: ~/.condarc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_todo.cfg:
    src: todo.cfg
    dst: ~/.todo.cfg
  d_yay:
    src: config/yay
    dst: ~/.config/yay
  d_scripts:
    src: scripts
    dst: ~/scripts
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_zsh_plugins.txt:
    src: zsh_plugins.txt
    dst: ~/.zsh_plugins.txt
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_zshalias:
    src: zshalias
    dst: ~/.zshalias
  d_joshuto:
    src: config/joshuto
    dst: ~/.config/joshuto
  d_gtk-2.0:
    src: config/gtk-2.0
    dst: ~/.config/gtk-2.0
    chmod: '700'
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '700'
  d_gtk-4.0:
    src: config/gtk-4.0
    dst: ~/.config/gtk-4.0
  d_direnv:
    src: config/direnv
    dst: ~/.config/direnv
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_screenlayout:
    src: screenlayout
    dst: ~/.screenlayout
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_zsh_history:
    src: zsh_history
    dst: ~/.zsh_history
    chmod: '600'
  f_zsh_plugins.zsh:
    src: zsh_plugins.zsh
    dst: ~/.zsh_plugins.zsh
  f_zshrc.bak:
    src: zshrc.bak
    dst: ~/.zshrc.bak
profiles:
  home:
    dotfiles:
    - ALL
    - d_wofi
    - d_sway
    - d_screenlayout
    - f_zsh_plugins.txt
    - f_zshenv
    - f_p10k.zsh
    - f_zshalias
    - d_joshuto
    - d_gtk-2.0
    - d_gtk-3.0
    - d_gtk-4.0
    - f_user-dirs.dirs
    - d_direnv
    - d_nvim
    - f_zsh_history
    - f_zsh_plugins.zsh
    - f_zshrc.bak
  laptop:
    dotfiles:
    - ALL
  uni:
    dotfiles:
    - ALL
  docker:
    dotfiles:
    - f_zshrc
    - f_starship.toml
    - f_condarc
    - f_radian_profile
    - f_renviron
    - f_rprofile
    - f_gitconfig
    - d_ipython
    - d_yay
