config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
dotfiles:
  f_rprofile:
    src: Rprofile
    dst: ~/.Rprofile
    link: link
  f_renviron:
    src: Renviron
    dst: ~/.Renviron
    link: link
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    link: link
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
    link: link
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
    link: link
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: link
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
    link: link
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    link: link_children
    upignore:
    - '*/completions'
    - '*/conf.d'
    - '*/functions'
    - '*/fish_variables'
  d_pypoetry:
    src: config/pypoetry
    dst: ~/.config/pypoetry
    link: link
  d_ipython:
    src: ipython
    dst: ~/.ipython
    link: link
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim/
    link: link_children
    upignore:
    - '*/undodir'
    - '*/pack'
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: link
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
    link: link
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_radian_profile:
    src: radian_profile
    dst: ~/.radian_profile
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_nvidia-force-full-composition.desktop:
    src: config/autostart/nvidia-force-full-composition.desktop
    dst: ~/.config/autostart/nvidia-force-full-composition.desktop
profiles:
  home:
    dotfiles:
    - ALL
  laptop:
    dotfiles:
    - ALL
  uni:
    dotfiles:
    - ALL
  docker:
    dotfiles:
    - d_fish
    - d_nvim
    - d_ranger
    - f_starship.toml
