config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  minversion: 1.9.0
dotfiles:
  f_rprofile:
    src: Rprofile
    dst: ~/.Rprofile
    link: absolute
  f_renviron:
    src: Renviron
    dst: ~/.Renviron
    link: absolute
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    link: absolute
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
    link: absolute
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
    link: absolute
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: absolute
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
    link: absolute
  d_ipython:
    src: ipython
    dst: ~/.ipython
    link: link_children
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim/
    link: link_children
    upignore:
      - "*/plugin"
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: absolute
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_radian_profile:
    src: radian_profile
    dst: ~/.radian_profile
  f_condarc:
    src: condarc
    dst: ~/.condarc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_profile:
    src: profile
    dst: ~/.profile
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_todo.cfg:
    src: todo.cfg
    dst: ~/.todo.cfg
  d_yay:
    src: config/yay
    dst: ~/.config/yay
  d_scripts:
    src: scripts
    dst: ~/scripts
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
profiles:
  home:
    dotfiles:
      - ALL
  laptop:
    dotfiles:
      - ALL
  uni:
    dotfiles:
      - ALL
  docker:
    dotfiles:
      - f_zshrc
      - d_nvim
      - d_ranger
      - f_starship.toml
      - f_condarc
      - f_radian_profile
      - f_renviron
      - f_rprofile
      - f_gitconfig
      - d_ipython
      - d_yay
