config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_rprofile:
    src: Rprofile
    dst: ~/.Rprofile
  f_renviron:
    src: Renviron
    dst: ~/.Renviron
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
  d_cmus:
    src: config/cmus
    dst: ~/.config/cmus
  d_nitrogen:
    src: config/nitrogen
    dst: ~/.config/nitrogen
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  d_fish:
    src: config/fish
    dst: ~/.config/fish
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_pypoetry:
    src: config/pypoetry
    dst: ~/.config/pypoetry
  d_ipython:
    src: ipython
    dst: ~/.ipython
  d_i3:
    src: i3
    dst: ~/.i3
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    link: link_children
profiles:
  home:
    dotfiles:
    - f_rprofile
    - f_renviron
    - d_kitty
    - f_picom.conf
    - d_autostart
    - d_cmus
    - d_nitrogen
    - d_rofi
    - d_zathura
    - d_fish
    - d_polybar
    - d_pypoetry
    - d_ipython
    - d_i3
    - d_nvim
