#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

  [blocks.segments.properties]
    style = 'full'

  [[blocks.segments]]
    type = 'git'
    foreground = 'black'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}{{ end }}{{ if gt .Ahead 0 }}{{ end }}</>'

  [blocks.segments.properties]
    fetch_status = true
    branch_icon = ''
    branch_identical_icon = ''
    branch_ahead_icon = ''
    branch_behind_icon = ''
    branch_gone_icon = ''

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  
  [[blocks.segments]] 
    type = 'python'
    foreground = 'black'
    background = 'transparent'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '($CONTAINER_ID)'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

  [blocks.segments.properties]
    threshold = 5000
    style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'magenta'
    background = 'transparent'
    template = '󰅪 '

[transient_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '󰅪 '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '> '
