destroy table inet host_filter

table inet host_filter {
    chain input {
        type filter hook input priority filter; policy drop;

        iifname "lo" accept
        ct state established,related accept
        ct state invalid drop

        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept

        iifname "tailscale0" accept
        ip saddr 192.168.0.0/24 tcp dport 22 accept

        udp dport { 5353, 5355 } ip saddr 192.168.0.0/24 accept
        tcp dport 5355 ip saddr 192.168.0.0/24 accept
    }
}
