general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && sleep 3 && hyprctl dispatch 'hl.dsp.dpms({ action = "off", monitor = "DP-1" })' && sleep 1 && hyprctl dispatch 'hl.dsp.dpms({ action = "on", monitor = "DP-1" })'
    ignore_systemd_inhibit = false
    ignore_dbus_inhibit = false
    ignore_wayland_inhibit = false
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
