return {
	defaults = {
		vimgrep_arguments = {
			"rg",
			"--color=never",
			"--no-heading",
			"--with-filename",
			"--line-number",
			"--column",
			"--smart-case",
			"--no-ignore-vcs",
			"-g=!data",
			"-g=!logs",
			"-g=!*.docx",
			"-g=!*.pdf",
		},
		prompt_prefix = ":: ",
		selection_caret = "| ",
		entry_prefix = "  ",
		initial_mode = "insert",
		selection_strategy = "reset",
		sorting_strategy = "ascending",
		layout_strategy = "bottom_pane",
		winblend = 0,
		border = true,
		borderchars = {
			prompt = { "─", " ", "─", " ", " ", " ", " ", " " },
			results = { "─", " ", " ", " ", " ", " ", " ", " " },
			preview = { "─", " ", " ", " ", " ", " ", " ", " " },
		},
		color_devicons = true,
	},
	pickers = {
		find_files = {
			find_command = {
				"fd",
				"--type",
				"f",
				"--strip-cwd-prefix",
				"--no-ignore",
				"--exclude=data",
				"--exclude=logs",
				"--exclude=*.docx",
				"--exclude=*.pdf",
			},
		},
	},
}
