#!/bin/bash
useradd -m cjber

# Generally, refreshing without sync'ing is discouraged, but we've a clean
# environment here.
pacman -Sy --noconfirm archlinux-keyring && \
    pacman -Sy --noconfirm base-devel git go && \
    pacman -Syu --noconfirm

echo "cjber ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/cjber
su cjber


# Auto-fetch GPG keys (for checking signatures):
mkdir .gnupg && \
    touch .gnupg/gpg.conf && \
    echo "keyserver-options auto-key-retrieve" > .gnupg/gpg.conf

# Install yay (for building AUR dependencies):
git clone https://aur.archlinux.org/yay.git && \
    cd yay && \
    makepkg --noconfirm && \
    sudo pacman -U yay*.pkg.* --noconfirm && \
    cd && \
    git clone https://github.com/cjber/dotfiles.git && \
    cd dotfiles/restore && \
    chmod +x * && \
    bash restore_all && \
    bash dots

yay -S --needed --noconfirm - < applist
