[symlinks]
"config/containers/podman/.keep" = "/home/cjber/.config/containers/podman/.keep"
"config/containers/registries.conf" = "/home/cjber/.config/containers/registries.conf"
"config/containers/storage.conf" = "/home/cjber/.config/containers/storage.conf"
"config/hypr/hypridle.conf" = "/home/cjber/.config/hypr/hypridle.conf"
"config/hypr/hyprland.conf" = "/home/cjber/.config/hypr/hyprland.conf"
"config/hypr/hyprlock.conf" = "/home/cjber/.config/hypr/hyprlock.conf"
"config/hypr/screenshot.sh" = "/home/cjber/.config/hypr/screenshot.sh"
"config/kitty/kitty.conf" = "/home/cjber/.config/kitty/kitty.conf"
"config/nvim/.stylua.toml" = "/home/cjber/.config/nvim/.stylua.toml"
"config/nvim/LICENSE" = "/home/cjber/.config/nvim/LICENSE"
"config/nvim/README.md" = "/home/cjber/.config/nvim/README.md"
"config/nvim/colors/oxide.lua" = "/home/cjber/.config/nvim/colors/oxide.lua"
"config/nvim/ftplugin/python.lua" = "/home/cjber/.config/nvim/ftplugin/python.lua"
"config/nvim/ftplugin/quarto.lua" = "/home/cjber/.config/nvim/ftplugin/quarto.lua"
"config/nvim/init.lua" = "/home/cjber/.config/nvim/init.lua"
"config/nvim/lsp/pyright.lua" = "/home/cjber/.config/nvim/lsp/pyright.lua"
"config/nvim/lsp/ruff.lua" = "/home/cjber/.config/nvim/lsp/ruff.lua"
"config/nvim/lua/configs/autosave.lua" = "/home/cjber/.config/nvim/lua/configs/autosave.lua"
"config/nvim/lua/configs/avante.lua" = "/home/cjber/.config/nvim/lua/configs/avante.lua"
"config/nvim/lua/configs/blink.lua" = "/home/cjber/.config/nvim/lua/configs/blink.lua"
"config/nvim/lua/configs/codecompanion.lua" = "/home/cjber/.config/nvim/lua/configs/codecompanion.lua"
"config/nvim/lua/configs/conform.lua" = "/home/cjber/.config/nvim/lua/configs/conform.lua"
"config/nvim/lua/configs/gitsigns.lua" = "/home/cjber/.config/nvim/lua/configs/gitsigns.lua"
"config/nvim/lua/configs/lazy.lua" = "/home/cjber/.config/nvim/lua/configs/lazy.lua"
"config/nvim/lua/configs/lint.lua" = "/home/cjber/.config/nvim/lua/configs/lint.lua"
"config/nvim/lua/configs/lsp-rename.lua" = "/home/cjber/.config/nvim/lua/configs/lsp-rename.lua"
"config/nvim/lua/configs/lualine.lua" = "/home/cjber/.config/nvim/lua/configs/lualine.lua"
"config/nvim/lua/configs/mcphub.lua" = "/home/cjber/.config/nvim/lua/configs/mcphub.lua"
"config/nvim/lua/configs/oil.lua" = "/home/cjber/.config/nvim/lua/configs/oil.lua"
"config/nvim/lua/configs/peek.lua" = "/home/cjber/.config/nvim/lua/configs/peek.lua"
"config/nvim/lua/configs/snacks.lua" = "/home/cjber/.config/nvim/lua/configs/snacks.lua"
"config/nvim/lua/configs/treesitter-textobjects.lua" = "/home/cjber/.config/nvim/lua/configs/treesitter-textobjects.lua"
"config/nvim/lua/configs/treesitter.lua" = "/home/cjber/.config/nvim/lua/configs/treesitter.lua"
"config/nvim/lua/configs/yarepl.lua" = "/home/cjber/.config/nvim/lua/configs/yarepl.lua"
"config/nvim/lua/mappings.lua" = "/home/cjber/.config/nvim/lua/mappings.lua"
"config/nvim/lua/options.lua" = "/home/cjber/.config/nvim/lua/options.lua"
"config/nvim/lua/plugins/init.lua" = "/home/cjber/.config/nvim/lua/plugins/init.lua"
"config/nvim/mcpservers.json" = "/home/cjber/.config/nvim/mcpservers.json"
"config/nvim/pyproject.toml" = "/home/cjber/.config/nvim/pyproject.toml"
"config/nvim/queries/python/injections.scm" = "/home/cjber/.config/nvim/queries/python/injections.scm"
"config/nvim/snips/package.json" = "/home/cjber/.config/nvim/snips/package.json"
"config/nvim/snips/snippets/python.json" = "/home/cjber/.config/nvim/snips/snippets/python.json"
"config/nvim/snips/snippets/quarto.json" = "/home/cjber/.config/nvim/snips/snippets/quarto.json"
"config/nvim/uv.lock" = "/home/cjber/.config/nvim/uv.lock"
"config/paru/paru.conf" = "/home/cjber/.config/paru/paru.conf"
"config/rofi/config.rasi" = "/home/cjber/.config/rofi/config.rasi"
"config/tmux/tmux.conf" = "/home/cjber/.config/tmux/tmux.conf"
"config/waybar/main.jsonc" = "/home/cjber/.config/waybar/main.jsonc"
"config/waybar/rclone-status.sh" = "/home/cjber/.config/waybar/rclone-status.sh"
"config/waybar/shadcn.css" = "/home/cjber/.config/waybar/shadcn.css"
"config/waybar/side.jsonc" = "/home/cjber/.config/waybar/side.jsonc"
"config/waybar/style-base.css" = "/home/cjber/.config/waybar/style-base.css"
"config/waybar/style.css" = "/home/cjber/.config/waybar/style.css"
"config/waybar/tailscale-status.sh" = "/home/cjber/.config/waybar/tailscale-status.sh"
"config/waybar/updates.sh" = "/home/cjber/.config/waybar/updates.sh"
"config/yazi/flavors/.keep" = "/home/cjber/.config/yazi/flavors/.keep"
"config/yazi/plugins/.keep" = "/home/cjber/.config/yazi/plugins/.keep"
"config/yazi/theme.toml" = "/home/cjber/.config/yazi/theme.toml"
"config/yazi/yazi.toml" = "/home/cjber/.config/yazi/yazi.toml"
gitconfig = "/home/cjber/.gitconfig"
"ipython/profile_default/ipython_config.py" = "/home/cjber/.ipython/profile_default/ipython_config.py"
"vale.ini" = "/home/cjber/.vale.ini"
"zsh_plugins.txt" = "/home/cjber/.zsh_plugins.txt"
zshalias = "/home/cjber/.zshalias"
zshenv = "/home/cjber/.zshenv"
zshrc = "/home/cjber/.zshrc"

[templates]
