[behavior]
global-python = true
use-uv = true

[default]
toolchain = "cpython@3.12"

[[sources]]
name = "nvidia"
url = "https://pypi.nvidia.com"

[[sources]]
name = "nvidia-nightly"
url = "https://pypi.anaconda.org/rapidsai-wheels-nightly/simple"
