model: ollama:llama3.1:8b
save: false
temperature: 0.1

clients:
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
    api_key: xxx
    models:
      - name: deepseek-r1:8b
        max_input_tokens: 131072
        supports_reasoning: true
      - name: deepseek-r1:14b
        max_input_tokens: 131072
        supports_reasoning: true
      - name: llama3.1:8b
        max_input_tokens: 128000
      - name: qwen3:8b
        max_input_tokens: 40000
      - name: gemma4:26b-a4b-it-q8_0
        max_input_tokens: 131072
        supports_vision: true
